---
title: processing raw data to package data
---

```{r include=FALSE}
assertthat::assert_that(
    knitr::current_input() %>% paste0('R-raw/', .) %>% file.exists(),
    msg = 'Please set knitr root directory to project directory! You may try running `rmarkdown::render("data-raw/data.Rmd")` at project directory or clicking `Knit` button on the top of this document in RStudio.'
)
```

```{r clean, include=FALSE}
dir('data', full.names = T) %>% file.remove()
rm(list = ls(envir = globalenv(), all = T))
```

Process you raw data here.

```{r suggest_refer}
suggest_refer <- tibble::tribble(
	~full,
    'ENST00000408438.1|MIR1228-201|73',
    'ENST00000385271.1|MIR16-1-201|89',
    'ENST00000607334.3|MIR15A-201|83',
    'ENST00000385059.1|MIR451A-201|72',
    'ENST00000362134.1|MIR21-201|72',
    'ENST00000385245.1|MIR23A-201|73',
    'ENST00000385045.1|MIR15B-201|98',
    'ENST00000362117.1|MIR16-2-201|81',
    'ENST00000384832.1|MIR23B-201|97',
    'ENST00000579846.3|MIR23C-201|100'
) %>% dplyr::mutate(id = stringr::str_extract(full, '[^|]+')) %>%
	dplyr::mutate(name = stringr::str_remove(full, '^[^\\|]+\\|')) %>%
	dplyr::mutate(name = stringr::str_remove(name, '\\|[^\\|]+$')) %>% 
	dplyr::mutate(name = stringr::str_remove(name, '-\\d+$')) %T>% print

usethis::use_data(suggest_refer, overwrite = TRUE)
```


```{r rna_type}
rna_type <-  readr::read_rds('data-raw/rna_type.rds') %T>% print

usethis::use_data(rna_type, overwrite = TRUE)
```

```{r}
set.seed(0)

n_gene = 1000
n_sample = 50;

#" I use two sample_n() to roughly make sure every type of RNA is sampled
sim_mat <- rpois(n_gene*n_sample, 5) %>% matrix(ncol = n_sample) %T>%
	{colnames(.) <- paste0('Sample_', seq_len(n_sample))} %T>% 
	{rownames(.) <- rna_type %>% 
		dplyr::group_by(gene_type) %>% dplyr::sample_n(n_gene, T) %>%
		.$transcript_id %>% sample(n_gene) %>% 
		c(suggest_refer$id) %>% unique %>% sample(n_gene)
	} %T>% print



sim_class <- c('Colorectal Cancer', 'Healthy Control', 'Prostate Cancer', 'Pancreatic Cancer');
sim_sample_class <- tibble::tibble(
	sample_id = colnames(sim_mat), label = sample(sim_class, length(sample_id), T)
) %T>% print


usethis::use_data(sim_mat, sim_sample_class, overwrite = TRUE)
```




```{r rebuild, include=FALSE}
devtools::document() # you may also have edited data documentation
system('R CMD INSTALL --no-multiarch --with-keep.source .')
devtools::reload();
devtools::test();
```




